package WebServer

import (
	_ "github.com/aerosystems/mail-service/docs" // docs are generated by Swag CLI, you have to import it.
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	docsGroup := e.Group("/docs")
	docsGroup.Use(BasicAuth)
	docsGroup.GET("/*", echoSwagger.WrapHandler)

	e.POST("/v1/feedback", app.SendFeedback)

	return e
}
